platformName: Android
#模拟器
platformVersion: 5.1.1
deviceName: 127.0.0.1:21513

#mx4真机
#platformVersion: 5.1
#udid: 750BBKL22GDN
#deviceName: MX4

appname: dr.fone3.2.0.apk
noReset: False
unicodeKeyboard: True
resetKeyboard: True

appPackage: com.wondershare.drfone
appActivity: com.wondershare.drfone.ui.activity.WelcomeActivity
ip: 127.0.0.1
port: 4723