platformName: Android
#模拟器
platformVersion: 5.1.1
deviceName: 127.0.0.1:21503

#mx4真机
#platformVersion: 5.1
#udid: 750BBKL22GDN
#deviceName: MX4

appname: weixin.apk
noReset: True
unicodeKeyboard: True
resetKeyboard: True

appPackage: com.tencent.mm
appActivity: com.tencent.mm.ui.LauncherUI
ip: 127.0.0.1
port: 4723